version: '3'
services:
  selenium:
    image: ruby:2.3.8
    command: /usr/local/bin/test.sh
    volumes:
      - "./test.sh:/usr/local/bin/test.sh"
      - "./sampleTest.rb:/usr/src/sampleTest.rb"
    environment:
      # Change endpoint according to your environment
      - "ZALENIUM_HD=192.168.43.36:30299"
