apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-mounted
  labels:
    name: zalenium-mounted
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  # Change according to your environment
  hostPath:
    path: "/tmp/zalenium/mounted"
