apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zalenium-mounted
  namespace: zalenium
spec:
  storageClassName: ""
  selector:
    matchLabels:
      name: zalenium-mounted
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
