apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
      name: slavelistener
  selector:
    app: jenkins
