apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zalenium.fullname" . }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "zalenium.fullname" . }}
rules:
  - verbs: ["create", "list", "get", "delete"]
    apiGroups: [""]
    resources: ["pods", "pods/exec"]
  - verbs: ["list", "create", "delete", "get"]
    apiGroups: [""]
    resources: ["services"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "zalenium.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "zalenium.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "zalenium.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
