apiVersion: v1
kind: Service
metadata:
  name: {{ template "zalenium.fullname" . }}
  labels:
    app: "{{ template "zalenium.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: zalenium
    port: {{ .Values.service.zalenium.port }}
    protocol: TCP
    targetPort: {{ .Values.service.zalenium.targetPort }}
  - name: register
    port: {{ .Values.service.register.port }}
    protocol: TCP
    targetPort: {{ .Values.service.register.targetPort }}
  sessionAffinity: {{ .Values.service.sessionAffinity | quote }}
  selector:
    app: "{{ template "zalenium.name" . }}"
    role: "grid"
